version: "3.9"

services:
  streaming:
    image: bluenviron/mediamtx:latest-alpine
    container_name: streaming
    ports:
      - "1935:1935"
      - "8888:8888"
    volumes:
      - ./hls:/hls
    restart: unless-stopped

  ssai:
    image: ghcr.io/westerncoastal/stream-stack/ssai:latest
    container_name: ssai
    depends_on:
      - streaming
    environment:
      - SERVER_IP=${SERVER_IP}
    volumes:
      - ./hls:/hls
      - ./ads:/ads
    ports:
      - "4000:4000"
    restart: unless-stopped

  revive-db:
    image: mariadb:10.6
    container_name: revive-db
    environment:
      MYSQL_DATABASE: revive
      MYSQL_USER: revive
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped

  revive:
    image: reviveadserver/revive-adserver:latest
    container_name: revive
    depends_on:
      - revive-db
    ports:
      - "8081:80"
    volumes:
      - ./revive_conf:/var/www/html/var
    restart: unless-stopped
