worker_processes auto;

events { worker_connections 1024; }

rtmp {
    server {
        listen 1935;

        application live {
            live on;

            hls on;
            hls_path /tmp/hls;
            hls_fragment 2;
        }
    }
}

http {
    server {
        listen 80;

        location /hls {
            root /tmp;
        }

        location / {
            root /usr/share/nginx/html;
        }
    }
}
