// scripts/repomix-to-md.js
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const INPUT_FILE = path.resolve("repomix-output.xml");
const OUTPUT_FILE = path.resolve("docs/repomix-summary.md");

function getGitInfo() {
  try {
    const commit = execSync("git rev-parse --short HEAD").toString().trim();
    const branch = execSync("git rev-parse --abbrev-ref HEAD").toString().trim();
    const date = new Date().toISOString();
    return { commit, branch, date };
  } catch {
    return { commit: "unknown", branch: "unknown", date: new Date().toISOString() };
  }
}

function xmlToMarkdown(xml) {
  // very lightweight parser (Repomix XML is structured but not huge)
  const files = [];
  const fileRegex = /<file path="([^"]+)">([\s\S]*?)<\/file>/g;

  let match;
  while ((match = fileRegex.exec(xml)) !== null) {
    const filePath = match[1];
    const content = match[2]
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .trim();

    files.push({ filePath, content });
  }

  let md = `# 📦 Repomix Repository Snapshot\n\n`;

  const git = getGitInfo();
  md += `> Auto-generated by CI\n`;
  md += `> Branch: **${git.branch}** | Commit: **${git.commit}**\n`;
  md += `> Generated: ${git.date}\n\n---\n\n`;

  md += `## 📁 File Overview\n\n`;

  for (const f of files) {
    md += `### \`${f.filePath}\`\n\n`;
    md += "```text\n";
    md += f.content.slice(0, 4000); // prevent huge docs
    md += "\n```\n\n";
  }

  return md;
}

function main() {
  if (!fs.existsSync(INPUT_FILE)) {
    console.error("❌ Repomix output not found:", INPUT_FILE);
    process.exit(1);
  }

  const xml = fs.readFileSync(INPUT_FILE, "utf-8");
  const md = xmlToMarkdown(xml);

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, md);

  console.log("✅ Docs generated:", OUTPUT_FILE);
}

main();
